swagger: '2.0'
host: api.instagram.com
paths:
  '/locations/{location-id}':
    get:
      description: Get information about a location.
      responses:
        '200':
          description: Location information response.
          x-internal: true
          schema:
            $ref: '#/definitions/MediaListResponse'
definitions:
  MediaListResponse:
    properties:
      data:
        description: List of media entries
    type: object
