openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition. Valid.
  version: 1.0

paths:
  /ping/{id}:
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: string
            enum: [user, poweruser, admin]
          required: true
      responses:
        '200':
          description: example description
  /ping/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: example description
  
