openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition. Valid.
  version: 1.0

paths:
  '/ping':
    get:
      responses:
        '500':
          description: example description
  /pet:
    post:
      responses:
        '400':
          description: example description