
# https://swagger.io/docs/specification/openapi-extensions/

apiDefinitions:
  main: openapi.yaml

lint:
  rules:
    bundler:
      nameConflicts: off
    debug-info: off

    no-extra-fields: on #By default, custom fields, not defined within OpenAPI specification can be included only using x- prefix. 
    no-$ref-siblings: off

    suggest-possible-refs: off
    oas3-schema/parameter: off
    oas3-schema/external-docs: off
    operations-tags-alpabetical: off
    path-param-exists: off
    operation-2xx-response: off
    unique-parameter-names: off
    no-unused-schemas: off
    operation-operationId-unique: off
    path-declarations-must-exist: off
    string-matcher: off
    enum-match-type: off

    operation-tags-defined: off
    provide-contact: off

    camel-case-names: off
    parameter-description: off
    server-not-example: off
    api-servers: off
    license-url: off
    license-required: off
    model-description: off
    operation-description: off
    operation-operationId: off
    operation-tags: off
    servers-no-trailing-slash: off