openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition. Valid.
  version: 1.0
  license:
    name: Apache 2.0
    #url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  '/ping':
    get:
      responses:
        '200':
          description: example description