openapi: 3.0.2
info:
  x-redocly-overlay:
    path: overlay-info.yaml
  title: Example OpenAPI 3 definition. Valid.
  version: 1.0

paths:
  '/ping':
    get:
      responses:
        '200':
          description: example description