openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition. Valid.
  version: 1.0

paths:
  '/ping/{id}/{test}':
    get:
      parameters:
        - in: path
          name: test
          description: User id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: example description
components:
  schemas:
    User_aa:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string